baseURL = 'http://le-8-juin-2024.paris/'
languageCode = 'en-us'
theme = "coming-soon"

[params]
title = 'À Paris 3, le 8 juin 2024'
description = 'À 10h à la Mairie de Paris Centre, 2 rue Eugène Spuller, 75003 Paris'
favicon = 'image/icons/favicon.ico'
message = 'Eun-Bee & Henrick'
release = '2024-06-08T10:00:00'
background = 'image/background/paris-3.jpg'

socialIcons = [
    { name = "calendar", url = "event/a-paris-3.ics" },
    { name = "email", url = "eun-bee.et.henrick@le-8-juin-2024.paris" },
    { name = "github", url = "https://github.com/hnrck/le-8-juin-2024" },
] 

